sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start Creating an image with dockerfile"
    - docker build -t yoonjung/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true yoonjung/docker-react-app npm run test -- --covereage

after_success:
    - echo "Test Success"
