sudo: required

language: generic

services:
    - docker

before_install:
    - chmod +x gradlew
    - echo "start Creating an image with dockerfile"
    - docker build -t yoonjung/docker-react-app -f Dockerfile.dev

script:
    - docker run -e CI=true yoonjung/docker-react-app npm run test -- --covereage

after_success:
    - echo "Test Success"

deploy:
	provider: elasticbeanstalk
	region: "ap-northeast-2"
	app: "docker-react-app"
	env: "DockerReactApp-env"
	bucket_name: "elasticbeanstalk-ap..."
	bucket_path: "docker-react-app"
	on:
		branch: master